package homemenu;

import playgame.GamePanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author amarabjamal
 */
public class HomeMenuPanel extends javax.swing.JPanel {
    private JPanel mainPanel;
    private CardLayout cardLayout;
    private GamePanel gamePanel;

    /**
     * Creates new form HomeMenuPanel
     */
    public HomeMenuPanel() {
        initComponents();
    }

    public HomeMenuPanel(JPanel mainPanel, CardLayout cardLayout, GamePanel gamePanel) {
        initComponents();
        this.mainPanel = mainPanel;
        this.cardLayout = cardLayout;
        this.gamePanel = gamePanel;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playGameButton = new javax.swing.JButton();
        decorateRoomButton = new javax.swing.JButton();
        selectThemeButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        backgroundImage = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(960, 576));
        setMinimumSize(new java.awt.Dimension(960, 576));
        setPreferredSize(new java.awt.Dimension(960, 576));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playGameButton.setBackground(new java.awt.Color(242, 242, 242));
        playGameButton.setBorderPainted(false);
        playGameButton.setContentAreaFilled(false);
        playGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playGameButtonActionPerformed(evt);
            }
        });
        add(playGameButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 100, 60));

        decorateRoomButton.setBorderPainted(false);
        decorateRoomButton.setContentAreaFilled(false);
        decorateRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decorateRoomButtonActionPerformed(evt);
            }
        });
        add(decorateRoomButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 130, 40));

        selectThemeButton.setBorderPainted(false);
        selectThemeButton.setContentAreaFilled(false);
        selectThemeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectThemeButtonActionPerformed(evt);
            }
        });
        add(selectThemeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 100, 50));

        quitButton.setBorderPainted(false);
        quitButton.setContentAreaFilled(false);
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });
        add(quitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 100, 40));

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background/background.png"))); // NOI18N
        add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void playGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playGameButtonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(mainPanel, "PlayGame");
        gamePanel.setUpGame();
        gamePanel.startGameThread();
    }//GEN-LAST:event_playGameButtonActionPerformed

    private void decorateRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decorateRoomButtonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(mainPanel, "DecorateRoom");
    }//GEN-LAST:event_decorateRoomButtonActionPerformed

    private void selectThemeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectThemeButtonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(mainPanel, "SelectTheme");
    }//GEN-LAST:event_selectThemeButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JButton decorateRoomButton;
    private javax.swing.JButton playGameButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton selectThemeButton;
    // End of variables declaration//GEN-END:variables
}
